version: "3"

services:

  frontend:
    image: fhc/frontend
    build:
      context: frontend
    ports:
      - ${FRONTEND_LOCAL_PORT}:80
    depends_on:
      - backend
    volumes:
      - ./frontend/static:/app/static:ro

  backend:
    image: fhc/backend
    ports:
      - ${BACKEND_LOCAL_PORT}:8000
    build:
      context: ./backend
    depends_on:
      - rabbitmq
    volumes:
      - ./backend/service:/usr/src/app:ro

  db:
    image: fhc/db
    build:
      dockerfile: ./db/Dockerfile

  rabbitmq:
    image: fhc/rabbitmq
    build:
      context: ./rabbitmq
    depends_on:
      - dbwriter

  dbwriter:
    image: fhc/dbwriter
    build:
      context: ./dbwriter
    depends_on:
      - db
